<h2 id="try">Try</h2>

<p>Arrow has <a href="http://arrow-kt.io/docs/patterns/error_handling/">lots of different types of error handling and reporting</a>, which allows you to choose the best strategy for your situation.</p>

<p>For example, we have <code class="highlighter-rouge">Option</code> to model the absence of a value, or <code class="highlighter-rouge">Either</code> to model the return of a function as a type that may have been successful, or may have failed.</p>

<p>On the other hand, we have <code class="highlighter-rouge">Try</code>, which represents a computation that can result in an <code class="highlighter-rouge">A</code> result (as long as the computation is successful) or in an exception if something has gone wrong.</p>

<p>That is, there are only two possible implementations of <code class="highlighter-rouge">Try</code>: a <code class="highlighter-rouge">Try</code> instance where the operation has been successful, which is represented as <code class="highlighter-rouge">Success&lt;A&gt;</code>; or a <code class="highlighter-rouge">Try</code> instance where the computation has failed with a <code class="highlighter-rouge">Throwable</code>, which is represented as <code class="highlighter-rouge">Failure&lt;A&gt;</code>.</p>

<p>With just this explanation you might think that we are talking about an <code class="highlighter-rouge">Either&lt;Throwable, A&gt;</code>, and you are not wrong. <code class="highlighter-rouge">Try</code> can be implemented in terms of <code class="highlighter-rouge">Either</code>, but its use cases are very different.</p>

<p>If we know that an operation could result in a failure, for example, because it is code from a library over which we have no control, or better yet, some method from the language itself. We can use <code class="highlighter-rouge">Try</code> as a substitute for the well-known <code class="highlighter-rouge">try-catch</code>, allowing us to rise to all its goodness.</p>

<p>The following example represents the typical case when consuming Java code, where domain errors are represented with exceptions.</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">open</span> <span class="kd">class</span> <span class="nc">GeneralException</span><span class="p">:</span> <span class="n">Exception</span><span class="p">()</span>

<span class="kd">class</span> <span class="nc">NoConnectionException</span><span class="p">:</span> <span class="n">GeneralException</span><span class="p">()</span>

<span class="kd">class</span> <span class="nc">AuthorizationException</span><span class="p">:</span> <span class="n">GeneralException</span><span class="p">()</span>

<span class="k">fun</span> <span class="n">checkPermissions</span><span class="p">()</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="n">AuthorizationException</span><span class="p">()</span>
<span class="p">}</span>

<span class="k">fun</span> <span class="n">getLotteryNumbersFromCloud</span><span class="p">():</span> <span class="n">List</span><span class="p">&lt;</span><span class="n">String</span><span class="p">&gt;</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="n">NoConnectionException</span><span class="p">()</span>
<span class="p">}</span>

<span class="k">fun</span> <span class="n">getLotteryNumbers</span><span class="p">():</span> <span class="n">List</span><span class="p">&lt;</span><span class="n">String</span><span class="p">&gt;</span> <span class="p">{</span>
    <span class="n">checkPermissions</span><span class="p">()</span>

    <span class="k">return</span> <span class="n">getLotteryNumbersFromCloud</span><span class="p">()</span>
<span class="p">}</span>
</code></pre></div></div>

<p>The traditional way to control this would be to use a <code class="highlighter-rouge">try-catch</code> block, as we have said before:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span> <span class="p">{</span>
    <span class="n">getLotteryNumbers</span><span class="p">()</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="n">e</span><span class="p">:</span> <span class="n">NoConnectionException</span><span class="p">)</span> <span class="p">{</span>
    <span class="c1">//...</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="n">e</span><span class="p">:</span> <span class="n">AuthorizationException</span><span class="p">)</span> <span class="p">{</span>
    <span class="c1">//...</span>
<span class="p">}</span>
</code></pre></div></div>

<p>However, we could use <code class="highlighter-rouge">Try</code> to retrieve the computation result in a much cleaner way:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">import</span> <span class="nn">arrow.*</span>
<span class="k">import</span> <span class="nn">arrow.core.*</span>

<span class="kd">val</span> <span class="py">lotteryTry</span> <span class="p">=</span> <span class="n">Try</span> <span class="p">{</span> <span class="n">getLotteryNumbers</span><span class="p">()</span> <span class="p">}</span>
<span class="n">lotteryTry</span>
<span class="c1">// Failure(exception=Line_1$AuthorizationException)</span>
</code></pre></div></div>

<p>By using <code class="highlighter-rouge">getOrDefault</code> we can give a default value to return, when the computation fails, similar to what we can also do with <code class="highlighter-rouge">Option</code> when there is no value:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">lotteryTry</span><span class="p">.</span><span class="n">getOrDefault</span> <span class="p">{</span> <span class="n">emptyList</span><span class="p">()</span> <span class="p">}</span>
<span class="c1">// []</span>
</code></pre></div></div>

<p>If the underlying failure is useful to determine the default value, <code class="highlighter-rouge">getOrElse</code> can be used:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">lotteryTry</span><span class="p">.</span><span class="n">getOrElse</span> <span class="p">{</span> <span class="n">ex</span><span class="p">:</span> <span class="n">Throwable</span> <span class="p">-&gt;</span> <span class="n">emptyList</span><span class="p">()</span> <span class="p">}</span>
<span class="c1">// []</span>
</code></pre></div></div>

<p><code class="highlighter-rouge">getOrElse</code> can generally be used anywhere <code class="highlighter-rouge">getOrDefault</code> is used, ignoring the exception if it’s not needed:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">lotteryTry</span><span class="p">.</span><span class="n">getOrElse</span> <span class="p">{</span> <span class="n">emptyList</span><span class="p">()</span> <span class="p">}</span>
<span class="c1">// []</span>
</code></pre></div></div>

<p>If you want to perform a check on a possible success, you can use <code class="highlighter-rouge">filter</code> to convert successful computations in failures if conditions aren’t met:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">lotteryTry</span><span class="p">.</span><span class="n">filter</span> <span class="p">{</span>
    <span class="n">it</span><span class="p">.</span><span class="n">size</span> <span class="p">&lt;</span> <span class="m">4</span>
<span class="p">}</span>
<span class="c1">// Failure(exception=Line_1$AuthorizationException)</span>
</code></pre></div></div>

<p>We can also use <code class="highlighter-rouge">recover</code> which allow us to recover from a particular error (we receive the error and have to return a new value):</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">lotteryTry</span><span class="p">.</span><span class="n">recover</span> <span class="p">{</span> <span class="n">exception</span> <span class="p">-&gt;</span>
    <span class="n">emptyList</span><span class="p">()</span>
<span class="p">}</span>
<span class="c1">// Success(value=[])</span>
</code></pre></div></div>

<p>Or if you have another different computation that can also fail, you can use <code class="highlighter-rouge">recoverWith</code> to recover from an error (as you do with <code class="highlighter-rouge">recover</code>, but in this case, returning a new <code class="highlighter-rouge">Try</code>):</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">enum</span> <span class="kd">class</span> <span class="nc">Source</span> <span class="p">{</span>
    <span class="n">CACHE</span><span class="p">,</span> <span class="n">NETWORK</span>
<span class="p">}</span>

<span class="k">fun</span> <span class="n">getLotteryNumbers</span><span class="p">(</span><span class="n">source</span><span class="p">:</span> <span class="n">Source</span><span class="p">):</span> <span class="n">List</span><span class="p">&lt;</span><span class="n">String</span><span class="p">&gt;</span> <span class="p">{</span>
    <span class="n">checkPermissions</span><span class="p">()</span>

    <span class="k">return</span> <span class="n">getLotteryNumbersFromCloud</span><span class="p">()</span>
<span class="p">}</span>

<span class="n">Try</span> <span class="p">{</span> <span class="n">getLotteryNumbers</span><span class="p">(</span><span class="n">Source</span><span class="p">.</span><span class="n">NETWORK</span><span class="p">)</span> <span class="p">}.</span><span class="n">recoverWith</span> <span class="p">{</span>
    <span class="n">Try</span> <span class="p">{</span> <span class="n">getLotteryNumbers</span><span class="p">(</span><span class="n">Source</span><span class="p">.</span><span class="n">CACHE</span><span class="p">)</span> <span class="p">}</span>
<span class="p">}</span>
<span class="c1">// Failure(exception=Line_1$AuthorizationException)</span>
</code></pre></div></div>

<p>When you want to handle both cases of the computation you can use <code class="highlighter-rouge">fold</code>. With <code class="highlighter-rouge">fold</code> we provide two functions, one for transforming a failure into a new value, the second one to transform the success value into a new one:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">lotteryTry</span><span class="p">.</span><span class="n">fold</span><span class="p">(</span>
    <span class="p">{</span> <span class="n">emptyList</span><span class="p">&lt;</span><span class="n">String</span><span class="p">&gt;()</span> <span class="p">},</span>
    <span class="p">{</span> <span class="n">it</span><span class="p">.</span><span class="n">filter</span> <span class="p">{</span> <span class="n">it</span><span class="p">.</span><span class="n">toIntOrNull</span><span class="p">()</span> <span class="p">!=</span> <span class="k">null</span> <span class="p">}</span> <span class="p">})</span>
<span class="c1">// []</span>
</code></pre></div></div>

<p>Or, as we have with <code class="highlighter-rouge">recoverWith</code>, we can use a version of <code class="highlighter-rouge">fold</code> which allows us to handle both cases with functions that return a new instance of <code class="highlighter-rouge">Try</code>, <code class="highlighter-rouge">transform</code>:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">lotteryTry</span><span class="p">.</span><span class="n">transform</span><span class="p">(</span>
    <span class="p">{</span> <span class="n">Try</span> <span class="p">{</span> <span class="n">it</span><span class="p">.</span><span class="n">map</span> <span class="p">{</span> <span class="n">it</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">}</span> <span class="p">}</span> <span class="p">},</span>
    <span class="p">{</span> <span class="n">Try</span><span class="p">.</span><span class="n">just</span><span class="p">(</span><span class="n">emptyList</span><span class="p">&lt;</span><span class="n">Int</span><span class="p">&gt;())</span> <span class="p">})</span>
<span class="c1">// Success(value=[])</span>
</code></pre></div></div>

<p>Lastly, Arrow contains <code class="highlighter-rouge">Try</code> instances for many useful typeclasses that allows you to use and transform fallibale values:</p>

<p><a href="/docs/typeclasses/functor/"><code class="highlighter-rouge">Functor</code></a></p>

<p>Transforming the value, if the computation is a success:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">import</span> <span class="nn">arrow.typeclasses.*</span>

<span class="n">Try</span><span class="p">.</span><span class="n">functor</span><span class="p">().</span><span class="n">run</span> <span class="p">{</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"3"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">}.</span><span class="n">map</span> <span class="p">{</span> <span class="n">it</span> <span class="p">+</span> <span class="m">1</span><span class="p">}</span> <span class="p">}</span>
<span class="c1">// Success(value=4)</span>
</code></pre></div></div>

<p><a href="/docs/typeclasses/applicative/"><code class="highlighter-rouge">Applicative</code></a></p>

<p>Computing over independent values:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">Try</span><span class="p">.</span><span class="n">applicative</span><span class="p">().</span><span class="n">tupled</span><span class="p">(</span><span class="n">Try</span> <span class="p">{</span> <span class="s">"3"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">},</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"5"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">},</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"nope"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">})</span>
<span class="c1">// Failure(exception=java.lang.NumberFormatException: For input string: "nope")</span>
</code></pre></div></div>

<p><a href="/docs/_docs/typeclasses/monad/"><code class="highlighter-rouge">Monad</code></a></p>

<p>Computing over dependent values ignoring failure:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">Try</span><span class="p">.</span><span class="n">monad</span><span class="p">().</span><span class="n">binding</span> <span class="p">{</span>
    <span class="kd">val</span> <span class="py">a</span> <span class="p">=</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"3"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">}.</span><span class="n">bind</span><span class="p">()</span>
    <span class="kd">val</span> <span class="py">b</span> <span class="p">=</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"4"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">}.</span><span class="n">bind</span><span class="p">()</span>
    <span class="kd">val</span> <span class="py">c</span> <span class="p">=</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"5"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">}.</span><span class="n">bind</span><span class="p">()</span>

    <span class="n">a</span> <span class="p">+</span> <span class="n">b</span> <span class="p">+</span> <span class="n">c</span>
<span class="p">}</span> <span class="c1">// Success(value=12)</span>
</code></pre></div></div>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">Try</span><span class="p">.</span><span class="n">monad</span><span class="p">().</span><span class="n">binding</span> <span class="p">{</span>
    <span class="kd">val</span> <span class="py">a</span> <span class="p">=</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"none"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">}.</span><span class="n">bind</span><span class="p">()</span>
    <span class="kd">val</span> <span class="py">b</span> <span class="p">=</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"4"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">}.</span><span class="n">bind</span><span class="p">()</span>
    <span class="kd">val</span> <span class="py">c</span> <span class="p">=</span> <span class="n">Try</span> <span class="p">{</span> <span class="s">"5"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span> <span class="p">}.</span><span class="n">bind</span><span class="p">()</span>

    <span class="n">a</span> <span class="p">+</span> <span class="n">b</span> <span class="p">+</span> <span class="n">c</span>
<span class="p">}</span> <span class="c1">// Failure(exception=java.lang.NumberFormatException: For input string: "none")</span>
</code></pre></div></div>

<p>Computing over dependent values that are automatically lifted to the context of <code class="highlighter-rouge">Try</code>:</p>

<div class="language-kotlin highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">Try</span><span class="p">.</span><span class="n">monadError</span><span class="p">().</span><span class="n">bindingCatch</span> <span class="p">{</span>
    <span class="kd">val</span> <span class="py">a</span> <span class="p">=</span> <span class="s">"none"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span>
    <span class="kd">val</span> <span class="py">b</span> <span class="p">=</span> <span class="s">"4"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span>
    <span class="kd">val</span> <span class="py">c</span> <span class="p">=</span> <span class="s">"5"</span><span class="p">.</span><span class="n">toInt</span><span class="p">()</span>

    <span class="n">a</span> <span class="p">+</span> <span class="n">b</span> <span class="p">+</span> <span class="n">c</span>
<span class="p">}</span> <span class="c1">// Failure(exception=java.lang.NumberFormatException: For input string: "none")</span>
</code></pre></div></div>

<h2 id="available-instances">Available Instances</h2>

<ul>
  <li><a href="/docs/typeclasses/show">Show</a></li>
  <li><a href="/docs/typeclasses/eq">Eq</a></li>
  <li><a href="/docs/typeclasses/applicative">Applicative</a></li>
  <li><a href="/docs/typeclasses/applicativeerror">ApplicativeError</a></li>
  <li><a href="/docs/typeclasses/foldable">Foldable</a></li>
  <li><a href="/docs/typeclasses/functor">Functor</a></li>
  <li><a href="/docs/typeclasses/monad">Monad</a></li>
  <li><a href="/docs/typeclasses/monaderror">MonadError</a></li>
  <li><a href="/docs/typeclasses/traverse">Traverse</a></li>
  <li><a href="/docs/optics/each">Each</a></li>
</ul>
